### ISSUE TITLE
Auto increase order number from backoffice

### ISSUE THREAD

**Issue by ghermans** [atabix/swretail-client-php#4]
i would like to suggest to auto increase the order number when no specific order number is given.

**Comment by jeroenatabix** [comment]
Thanks for your suggestion.

However, the order_number is a text field for the API, and allows for example "2019-A0789/2" as a valid order number.

Also, for this client to know what a next number should be, an extra request to the API would be needed to get all existing orders, and search for the biggest number. This is undesirable overhead for this client.

As the API requires an external order number, your application should keep track of orders (and numbers) in a local database.
